name: Build CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Deps
      uses: awalsh128/cache-apt-pkgs-action@v1.2.1
      with:
        packages: libssl-dev libuv1-dev gcc-10 g++-12 make zlib1g-dev libgtk-3-dev libwebkit2gtk-4.0-dev
        version: 1.0
    - uses: actions/checkout@v3
    - name: Pre Configure
      run: autoreconf --install
    - name: Configure
      run: ./configure
    - name: Make
      run: make CC=gcc-10 CXX=g++-12 LD=g++-12 CPP=g++-12
    - name: Run Tests
      run: make check
